import React, { useState } from 'react';
import { Logo } from './Logo'; import { DualStateDashboard } from './DualStateDashboard'; import { PayrollRoster } from './PayrollRoster'; import { PaystubData } from './PaystubModal'; import { WalletConnect } from './WalletConnect';
import { WalletState,CircuitCallState,PREPROD_CONTRACT_ADDRESS,PREPROD_CONTRACT_HEX_ID } from '../hooks/useMidnight';
import { ArrowLeft,BookOpen,Check,ChevronDown,ChevronUp,Code2,Copy,FileText,History,LayoutDashboard,LogOut,Menu,ShieldCheck,Users,Wallet,X } from 'lucide-react';
interface Props { wallet:WalletState; onConnect:()=>void; onDisconnect:()=>void; isWalletInstalled:boolean; privateWitnessValue:number; onWitnessChange:(v:number)=>void; publicCounterState:number; circuitState:CircuitCallState; onExecute:()=>void; onOpenPaystub:(d:PaystubData)=>void; onBackToWebsite:()=>void; }
type View='overview'|'payroll'|'transactions'|'proof'|'developer';
export const AppDashboard:React.FC<Props>=({wallet,onConnect,onDisconnect,isWalletInstalled,privateWitnessValue,onWitnessChange,publicCounterState,circuitState,onExecute,onOpenPaystub,onBackToWebsite})=>{
 const [view,setView]=useState<View>('payroll'); const [mobile,setMobile]=useState(false); const [technical,setTechnical]=useState(false); const [copied,setCopied]=useState(false);
 const nav:[View,string,React.ElementType][]=[['overview','Overview',LayoutDashboard],['payroll','Payroll runs',Users],['transactions','Transactions',History],['proof','Proof console',ShieldCheck],['developer','Developer settings',Code2]];
 const choose=(v:View)=>{setView(v);setMobile(false)}; const copy=()=>{navigator.clipboard.writeText(PREPROD_CONTRACT_ADDRESS);setCopied(true);setTimeout(()=>setCopied(false),1500)};
 const Sidebar=()=> <><div className="flex h-16 items-center border-b border-[var(--border)] px-5"><Logo size={30} showText/></div><nav className="flex-1 space-y-1 p-3" aria-label="Workspace navigation">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>choose(id)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${view===id?'bg-[var(--brand-soft)] text-white':'text-[var(--text-muted)] hover:bg-[var(--surface-2)] hover:text-white'}`} aria-current={view===id?'page':undefined}><Icon className={`h-4 w-4 ${view===id?'text-[#a995ff]':''}`}/>{label}</button>)}</nav><button onClick={onBackToWebsite} className="m-3 flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-[var(--text-muted)] hover:text-white"><ArrowLeft className="h-4 w-4"/>Back to website</button></>;
 return <div className="min-h-screen bg-[var(--canvas)] text-white lg:grid lg:grid-cols-[240px_1fr]"><aside className="sticky top-0 hidden h-screen border-r border-[var(--border)] bg-[var(--surface-1)] lg:flex lg:flex-col"><Sidebar/></aside>
  {mobile&&<div className="fixed inset-0 z-50 bg-black/60 lg:hidden" onClick={()=>setMobile(false)}><aside className="flex h-full w-72 flex-col bg-[var(--surface-1)]" onClick={e=>e.stopPropagation()}><div className="absolute left-[232px] top-3"><button onClick={()=>setMobile(false)} className="p-2" aria-label="Close navigation"><X/></button></div><Sidebar/></aside></div>}
  <div className="min-w-0"><header className="sticky top-0 z-40 flex h-16 items-center justify-between border-b border-[var(--border)] bg-[color:var(--canvas)]/95 px-4 backdrop-blur-md sm:px-6"><div className="flex items-center gap-3"><button onClick={()=>setMobile(true)} className="app-button-secondary p-2 lg:hidden" aria-label="Open navigation"><Menu className="h-5 w-5"/></button><div><p className="text-sm font-medium">Vansidian workspace</p><p className="hidden text-xs text-[var(--text-muted)] sm:block">Midnight preprod</p></div></div><div className="flex items-center gap-2">{wallet.isConnected?<><span className="hidden font-mono text-xs text-[var(--text-muted)] sm:block">{wallet.address?.slice(0,9)}…</span><button onClick={onDisconnect} className="app-button-secondary p-2" aria-label="Disconnect wallet"><LogOut className="h-4 w-4"/></button></>:<button onClick={onConnect} className="app-button-primary flex items-center gap-2 px-3.5 py-2 text-sm"><Wallet className="h-4 w-4"/>{wallet.isConnecting?'Connecting…':'Connect wallet'}</button>}</div></header>
  <main className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><div className="mb-6"><p className="text-sm text-[#a995ff]">Finance operations</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">{nav.find(n=>n[0]===view)?.[1]}</h1><p className="mt-1 text-sm text-[var(--text-muted)]">{view==='payroll'?'Review compensation and submit a private, verifiable payroll run.':'Confidential operations with verifiable public state.'}</p></div>
  {!wallet.isConnected&&<div className="mb-6"><WalletConnect wallet={wallet} onConnect={onConnect} onDisconnect={onDisconnect} isWalletInstalled={isWalletInstalled}/></div>}
  {(view==='overview'||view==='payroll')&&<PayrollRoster isConnected={wallet.isConnected} onDisburseBatch={async()=>onExecute()} isProcessing={circuitState.isCalling} onOpenPaystub={onOpenPaystub}/>} 
  {view==='proof'&&<DualStateDashboard privateWitnessValue={privateWitnessValue} onWitnessChange={onWitnessChange} publicCounterState={publicCounterState} circuitState={circuitState} onExecute={onExecute} isConnected={wallet.isConnected} onOpenPaystub={onOpenPaystub}/>} 
  {view==='transactions'&&<section className="app-card overflow-hidden"><div className="border-b border-[var(--border)] p-6"><h2 className="text-lg font-semibold">Transaction history</h2><p className="text-sm text-[var(--text-muted)]">Verified payroll state transitions.</p></div><div>{circuitState.history.map((tx,i)=><div key={i} className="flex flex-col gap-3 border-b border-[var(--border)] px-6 py-4 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-4 w-4 text-[var(--success)]"/><div><code className="text-sm">{tx.txHash}</code><p className="mt-1 text-xs text-[var(--text-muted)]">{tx.timestamp} · Verified proof</p></div></div><button onClick={()=>onOpenPaystub({certificateId:`CERT-${i+10482}`,txHash:tx.txHash,blockTimestamp:tx.timestamp,employeeName:'Verified recipient',disclosedAmount:tx.addedValue*100,circuitName:'processPayrollBatch (Compact v0.31.1)'})} className="app-button-secondary flex items-center justify-center gap-2 px-3 py-2 text-xs"><FileText className="h-3.5 w-3.5"/>View statement</button></div>)}</div></section>}
  {view==='developer'&&<section className="app-card overflow-hidden"><div className="p-6"><h2 className="text-lg font-semibold">Developer settings</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Network and contract configuration for this workspace.</p></div><button onClick={()=>setTechnical(!technical)} className="flex w-full items-center justify-between border-t border-[var(--border)] px-6 py-4 text-sm"><span className="flex items-center gap-2"><BookOpen className="h-4 w-4"/>Contract details</span>{technical?<ChevronUp className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}</button>{technical&&<div className="space-y-4 border-t border-[var(--border)] bg-[var(--surface-1)] p-6"><div><p className="mb-1 text-xs text-[var(--text-muted)]">Contract ID</p><code className="break-all text-xs">{PREPROD_CONTRACT_HEX_ID}</code></div><div><div className="mb-1 flex justify-between"><p className="text-xs text-[var(--text-muted)]">Contract address</p><button onClick={copy} className="flex items-center gap-1 text-xs text-[#a995ff]">{copied?<Check className="h-3 w-3"/>:<Copy className="h-3 w-3"/>}{copied?'Copied':'Copy'}</button></div><code className="break-all text-xs">{PREPROD_CONTRACT_ADDRESS}</code></div><div><p className="text-xs text-[var(--text-muted)]">Public ledger counter</p><p className="mt-1 text-xl font-semibold">{publicCounterState}</p></div></div>}</section>}
  </main></div></div>;
};
