import React, { useState } from 'react';
import { Check, ChevronDown, ChevronUp, Copy, Eye, EyeOff, FileText, LockKeyhole, ShieldCheck } from 'lucide-react';
import { CircuitCallState, PREPROD_CONTRACT_ADDRESS } from '../hooks/useMidnight';
import { PaystubData } from './PaystubModal';
interface Props { privateWitnessValue:number; onWitnessChange:(v:number)=>void; publicCounterState:number; circuitState:CircuitCallState; onExecute:()=>void; isConnected:boolean; onOpenPaystub?:(d:PaystubData)=>void; }
export const DualStateDashboard:React.FC<Props>=({privateWitnessValue,onWitnessChange,publicCounterState,circuitState,onExecute,isConnected,onOpenPaystub})=>{
 const [show,setShow]=useState(true); const [technical,setTechnical]=useState(false); const [copied,setCopied]=useState(false);
 const copy=()=>{navigator.clipboard.writeText(PREPROD_CONTRACT_ADDRESS);setCopied(true);setTimeout(()=>setCopied(false),1500)};
 const progress=circuitState.stage==='witness'?25:circuitState.stage==='proving'?60:circuitState.stage==='submitting'?86:circuitState.stage==='confirmed'?100:0;
 return <div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]">
  <section className="app-card overflow-hidden"><div className="border-b border-[var(--border)] p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-[#a995ff]">Private transaction</p><h2 className="mt-2 text-xl font-medium">Generate a state proof</h2></div><span className="status-success rounded-full px-2.5 py-1 text-xs">Preprod</span></div><p className="mt-2 text-sm text-[var(--text-muted)]">The witness is evaluated locally and never sent as plaintext.</p></div>
   <div className="space-y-7 p-6"><div><div className="mb-2 flex items-center justify-between"><label htmlFor="witness" className="text-sm font-medium">Private witness value</label><button onClick={()=>setShow(!show)} className="flex items-center gap-1.5 text-xs text-[var(--text-muted)] hover:text-white">{show?<EyeOff className="h-3.5 w-3.5"/>:<Eye className="h-3.5 w-3.5"/>}{show?'Hide':'Reveal'}</button></div><div className="relative"><span className="absolute left-4 top-1/2 -translate-y-1/2 text-xl text-[var(--text-muted)]">+</span><input id="witness" type={show?'number':'password'} value={privateWitnessValue} onChange={e=>onWitnessChange(Math.max(1,parseInt(e.target.value)||1))} className="w-full rounded-xl border border-[var(--border)] bg-[var(--canvas)] py-4 pl-9 pr-4 text-2xl font-medium focus:border-[#7657f6]"/></div><div className="mt-3 flex flex-wrap gap-2">{[1,5,10,25,50].map(v=><button key={v} onClick={()=>onWitnessChange(v)} className={`rounded-full border px-3 py-1.5 text-xs ${privateWitnessValue===v?'border-[#7657f6] bg-[var(--brand-soft)] text-[#c7bcff]':'border-[var(--border)] text-[var(--text-muted)] hover:text-white'}`}>+{v}</button>)}</div></div>
    <div className="rounded-xl border border-[var(--border)] bg-[var(--surface-1)] p-4"><div className="flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-[var(--text-muted)]"><LockKeyhole className="h-4 w-4 text-[#a995ff]"/>{circuitState.isCalling?'Proof in progress':'Local proving pipeline'}</span><span className="font-mono">{progress}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-[#7657f6] to-[#32b77c] transition-[width]" style={{width:`${progress}%`}}/></div><div className="mt-3 grid grid-cols-3 text-[10px] text-[var(--text-subtle)]"><span>Witness</span><span className="text-center">Prove</span><span className="text-right">Commit</span></div></div>
    {circuitState.error&&<div className="rounded-lg border border-red-500/25 bg-red-500/10 p-3 text-sm text-red-300">{circuitState.error}</div>}
    <button onClick={onExecute} disabled={!isConnected||circuitState.isCalling} className="app-button-primary w-full py-3.5 font-semibold">{circuitState.isCalling?'Generating proof…':isConnected?`Generate proof and submit +${privateWitnessValue}`:'Connect wallet to continue'}</button>
   </div>
   <button onClick={()=>setTechnical(!technical)} className="flex w-full items-center justify-between border-t border-[var(--border)] bg-[var(--surface-1)] px-6 py-4 text-sm text-[var(--text-muted)] hover:text-white" aria-expanded={technical}><span>Technical transaction details</span>{technical?<ChevronUp className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}</button>{technical&&<div className="border-t border-[var(--border)] bg-[var(--surface-1)] p-6 text-xs"><div className="flex items-start justify-between gap-4"><div><p className="text-[var(--text-muted)]">Contract address</p><code className="mt-1 block break-all">{PREPROD_CONTRACT_ADDRESS}</code></div><button onClick={copy} className="flex shrink-0 items-center gap-1 text-[#a995ff]">{copied?<Check className="h-3.5 w-3.5"/>:<Copy className="h-3.5 w-3.5"/>}{copied?'Copied':'Copy'}</button></div></div>}
  </section>
  <section className="app-card overflow-hidden"><div className="border-b border-[var(--border)] p-6"><p className="text-xs uppercase tracking-[.18em] text-[#73d7aa]">Verified ledger</p><div className="mt-3 flex items-end justify-between"><div><p className="text-sm text-[var(--text-muted)]">Public state</p><p className="mt-1 text-4xl font-medium tracking-tight">{publicCounterState}</p></div><span className="flex items-center gap-1.5 text-xs text-[#73d7aa]"><ShieldCheck className="h-4 w-4"/>Verified</span></div></div><div className="p-6"><div className="mb-4 flex items-center justify-between"><h3 className="font-medium">Recent activity</h3><span className="text-xs text-[var(--text-muted)]">{circuitState.history.length} records</span></div><div className="divide-y divide-[var(--border)]">{circuitState.history.slice(0,6).map((tx,i)=><div key={i} className="flex items-center justify-between gap-3 py-4"><div className="min-w-0"><p className="truncate font-mono text-xs">{tx.txHash}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{tx.timestamp} · Proof accepted</p></div><div className="flex items-center gap-2"><span className="font-mono text-xs text-[#73d7aa]">+{tx.addedValue}</span>{onOpenPaystub&&<button onClick={()=>onOpenPaystub({certificateId:`CERT-${i+30192}`,txHash:tx.txHash,blockTimestamp:tx.timestamp,employeeName:'Confidential disbursal',disclosedAmount:tx.addedValue*100,circuitName:'increment (Compact v0.31.1)'})} className="app-button-secondary p-2" aria-label="View verified statement"><FileText className="h-3.5 w-3.5"/></button>}</div></div>)}</div></div>
  </section>
 </div>;
};
