import React from 'react';
import { ArrowRight, Check, LockKeyhole, PlayCircle } from 'lucide-react';
interface HeroSectionProps { onConnectClick:()=>void; isConnected:boolean; onLaunchApp:()=>void; }
export const HeroSection:React.FC<HeroSectionProps> = ({onConnectClick,isConnected,onLaunchApp}) => <section id="hero" className="w-full border-b border-[var(--border)]">
  <div className="mx-auto grid max-w-7xl gap-14 px-4 py-20 sm:px-6 sm:py-28 lg:grid-cols-[1fr_0.9fr] lg:items-center lg:px-8">
    <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--surface-1)] px-3 py-1.5 text-xs text-[var(--text-muted)]"><LockKeyhole className="h-3.5 w-3.5 text-[#a995ff]"/>Confidential payroll infrastructure on Midnight</div>
      <h1 className="max-w-3xl text-4xl font-semibold leading-[1.08] tracking-[-0.04em] text-white sm:text-6xl">Private payroll,<br/>verifiable by design.</h1>
      <p className="mt-6 max-w-xl text-base leading-7 text-[var(--text-muted)] sm:text-lg">Run payroll without publishing employee compensation. Vansidian creates verifiable proofs for finance teams, employees, and auditors while sensitive data stays private.</p>
      <div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={onLaunchApp} className="app-button-primary flex items-center justify-center gap-2 px-5 py-3 font-semibold">Open workspace <ArrowRight className="h-4 w-4"/></button><a href="#documentation" className="app-button-secondary flex items-center justify-center gap-2 px-5 py-3 font-semibold"><PlayCircle className="h-4 w-4"/>View documentation</a></div>
      {!isConnected&&<button onClick={onConnectClick} className="mt-4 text-sm text-[var(--text-muted)] underline-offset-4 hover:text-white hover:underline">Or connect a Lace wallet</button>}
      <div className="mt-10 flex flex-wrap gap-x-6 gap-y-2 text-sm text-[var(--text-muted)]">{['No plaintext on-chain','Selective disclosure','Auditable state'].map(item=><span key={item} className="flex items-center gap-2"><Check className="h-4 w-4 text-[var(--success)]"/>{item}</span>)}</div>
    </div>
    <div className="app-card overflow-hidden p-2" aria-label="Payroll workspace preview"><div className="rounded-[10px] border border-[var(--border)] bg-[var(--canvas)]"><div className="flex items-center justify-between border-b border-[var(--border)] px-5 py-4"><div><p className="font-medium">September payroll</p><p className="text-xs text-[var(--text-muted)]">5 team members</p></div><span className="status-success rounded-full px-2.5 py-1 text-xs">Ready to prove</span></div><div className="grid grid-cols-3 gap-px border-b border-[var(--border)] bg-[var(--border)]">{[['Total payroll','$34,500'],['Employees','5'],['Exceptions','0']].map(([k,v])=><div key={k} className="bg-[var(--surface-1)] p-4"><p className="text-xs text-[var(--text-muted)]">{k}</p><p className="mt-1 text-lg font-semibold">{v}</p></div>)}</div><div className="p-5">{['Sarah Jenkins','David Kim','Elena Rostova','Marcus Vance'].map((name,i)=><div key={name} className="flex items-center justify-between border-b border-[var(--border)] py-3 last:border-0"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-[var(--brand-soft)] text-xs text-[#b7a8ff]">{name.split(' ').map(n=>n[0]).join('')}</span><span className="text-sm">{name}</span></div><span className="font-mono text-xs text-[var(--text-muted)]">${[9000,7800,6500,6000][i].toLocaleString()}</span></div>)}</div></div></div>
  </div>
</section>;
