import React from 'react';
import { ArrowRight, Check, Fingerprint, LockKeyhole, ShieldCheck, Users } from 'lucide-react';
interface HeroSectionProps { onConnectClick:()=>void; isConnected:boolean; onLaunchApp:()=>void; }
const people=[['SJ','Sarah Jenkins'],['DK','David Kim'],['ER','Elena Rostova'],['MV','Marcus Vance']];
export const HeroSection:React.FC<HeroSectionProps>=({onConnectClick,isConnected,onLaunchApp})=><section id="hero" className="w-full px-3 pb-16 sm:px-5">
 <div className="relative mx-auto max-w-[1380px] overflow-hidden rounded-b-[30px] border border-white/[.07] bg-[#0c0d14] px-5 pb-8 pt-14 sm:px-10 sm:pt-20 lg:px-14">
  <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_72%_22%,rgba(118,87,246,.22),transparent_34%),radial-gradient(circle_at_10%_0%,rgba(50,183,124,.08),transparent_25%)]"/>
  <div className="pointer-events-none absolute inset-0 opacity-[.035] bg-[linear-gradient(to_right,white_1px,transparent_1px),linear-gradient(to_bottom,white_1px,transparent_1px)] bg-[size:56px_56px]"/>
  <div className="relative grid items-center gap-14 lg:grid-cols-[.95fr_1.05fr]">
   <div className="max-w-2xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.05] px-3 py-1.5 text-xs text-[#c7bcff]"><ShieldCheck className="h-3.5 w-3.5"/>Private finance, publicly verifiable</div>
    <h1 className="text-5xl font-medium leading-[1.02] tracking-[-.055em] text-white sm:text-6xl lg:text-[76px]">Payroll privacy<br/><span className="bg-gradient-to-r from-[#b7a8ff] via-[#8f78ff] to-[#63d6a4] bg-clip-text text-transparent">starts here.</span></h1>
    <p className="mt-6 max-w-lg text-sm leading-6 text-[var(--text-muted)] sm:text-base">Run confidential payroll, prove every disbursement, and give auditors exactly what they need—without exposing employee compensation.</p>
    <div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={onLaunchApp} className="app-button-primary flex items-center justify-center gap-2 rounded-full px-6 py-3 font-semibold">Start a payroll run <ArrowRight className="h-4 w-4"/></button><a href="#how-it-works" className="app-button-secondary flex items-center justify-center rounded-full px-6 py-3 font-semibold">See how it works</a></div>
    {!isConnected&&<button onClick={onConnectClick} className="mt-4 text-xs text-[var(--text-muted)] hover:text-white">Connect a Lace wallet instead →</button>}
   </div>
   <div className="relative mx-auto w-full max-w-[620px] pb-10" aria-label="Vansidian workspace preview">
    <div className="absolute -inset-8 rounded-full bg-[#7657f6]/10 blur-3xl"/>
    <div className="relative ml-auto w-[92%] rounded-[28px] border border-white/10 bg-[#12141d]/90 p-3 shadow-[0_35px_90px_rgba(0,0,0,.45)] sm:w-[86%]">
     <div className="overflow-hidden rounded-[20px] border border-white/[.07] bg-[#090b10]"><div className="flex items-center justify-between border-b border-white/[.07] px-5 py-4"><div><p className="text-xs text-[var(--text-muted)]">September payroll</p><p className="mt-1 text-xl font-semibold">$34,500.00</p></div><span className="rounded-full bg-[#32b77c]/10 px-2.5 py-1 text-[10px] text-[#73d7aa]">Ready to prove</span></div>
      <div className="grid grid-cols-3 border-b border-white/[.07]"><div className="p-4"><p className="text-[10px] text-[var(--text-muted)]">Employees</p><p className="mt-1 font-semibold">5</p></div><div className="border-x border-white/[.07] p-4"><p className="text-[10px] text-[var(--text-muted)]">Exceptions</p><p className="mt-1 font-semibold">0</p></div><div className="p-4"><p className="text-[10px] text-[var(--text-muted)]">Pay date</p><p className="mt-1 font-semibold">Sep 30</p></div></div>
      <div className="p-4">{people.map(([initials,name],i)=><div key={name} className="flex items-center justify-between border-b border-white/[.06] py-3 last:border-0"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#7657f6]/15 text-[10px] text-[#b7a8ff]">{initials}</span><div><p className="text-xs font-medium">{name}</p><p className="text-[10px] text-[var(--text-muted)]">{['Engineering','Research','Product','Security'][i]}</p></div></div><span className="font-mono text-xs">${[9000,7800,6500,6000][i].toLocaleString()}</span></div>)}</div>
     </div>
    </div>
    <div className="absolute bottom-0 left-0 w-[55%] rounded-2xl border border-[#8f78ff]/25 bg-[#171827]/95 p-4 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-[10px] text-[var(--text-muted)]">Proof progress</p><p className="mt-1 text-sm font-semibold">Commitment ready</p></div><Fingerprint className="h-6 w-6 text-[#a995ff]"/></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full w-[82%] rounded-full bg-gradient-to-r from-[#7657f6] to-[#32b77c]"/></div><div className="mt-3 flex justify-between text-[9px] text-[var(--text-muted)]"><span>Private inputs</span><span>82%</span></div></div>
    <div className="absolute right-0 top-[36%] hidden rounded-xl border border-white/10 bg-[#f4f1ff] p-4 text-[#101118] shadow-xl sm:block"><p className="text-[9px] text-[#656779]">Batch commitment</p><p className="mt-1 font-mono text-xs font-semibold">0x91b7…ae42</p><div className="mt-3 flex items-center gap-1.5 text-[9px] text-[#24805a]"><Check className="h-3 w-3"/>Validated locally</div></div>
   </div>
  </div>
  <div className="relative mt-16 grid grid-cols-2 gap-6 border-t border-white/[.07] pt-8 sm:grid-cols-4">{[[LockKeyhole,'0','Plaintext leaks'],[Users,'5','Team members'],[Fingerprint,'1','Batch proof'],[ShieldCheck,'100%','Auditable']].map(([Icon,value,label])=><div key={String(label)} className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#7657f6]/12"><Icon className="h-4 w-4 text-[#b7a8ff]"/></span><div><p className="text-2xl font-medium tracking-tight">{String(value)}</p><p className="text-[10px] uppercase tracking-[.16em] text-[var(--text-muted)]">{String(label)}</p></div></div>)}</div>
 </div>
</section>;
