import React, { useMemo, useState } from 'react';
import { Check, ChevronDown, ChevronUp, FileText, Search, ShieldCheck } from 'lucide-react';
import { PaystubData } from './PaystubModal';
interface Employee { id:string; name:string; role:string; department:string; salary:number; bonus:number; }
const INITIAL_EMPLOYEES:Employee[]=[
  {id:'emp-1',name:'Sarah Jenkins',role:'Lead Cryptographer',department:'Engineering',salary:8500,bonus:500},
  {id:'emp-2',name:'David Kim',role:'ZK Circuit Architect',department:'Research',salary:7400,bonus:400},
  {id:'emp-3',name:'Elena Rostova',role:'UI/UX Systems Engineer',department:'Product',salary:6200,bonus:300},
  {id:'emp-4',name:'Marcus Vance',role:'Smart Contract Auditor',department:'Security',salary:5800,bonus:200},
  {id:'emp-5',name:'Chloe Dupont',role:'Regulatory Compliance Officer',department:'Legal',salary:5100,bonus:100},
];
interface Props { isConnected:boolean; onDisburseBatch:(data:{totalAmount:number;employeeCount:number;batchRootHash:string})=>Promise<void>; isProcessing:boolean; onOpenPaystub:(data:PaystubData)=>void; isPublicMode?:boolean; }
export const PayrollRoster:React.FC<Props>=({isConnected,onDisburseBatch,isProcessing,onOpenPaystub,isPublicMode=false})=>{
  const [employees,setEmployees]=useState(INITIAL_EMPLOYEES); const [query,setQuery]=useState(''); const [details,setDetails]=useState(false);
  const shown=useMemo(()=>employees.filter(e=>`${e.name} ${e.role} ${e.department}`.toLowerCase().includes(query.toLowerCase())),[employees,query]);
  const total=employees.reduce((s,e)=>s+e.salary+e.bonus,0); const root='0x'+Array.from({length:8},(_,i)=>((total*31+i*17)%65536).toString(16).padStart(4,'0')).join('')+'f92e4a1b0c3d5e8f';
  const toggle=(id:string)=>setEmployees(v=>v.map(e=>e.id===id?{...e,bonus:e.bonus?0:500}:e));
  const submit=async()=>{if(!isConnected||isProcessing)return; await onDisburseBatch({totalAmount:total,employeeCount:employees.length,batchRootHash:root}); onOpenPaystub({certificateId:`CERT-${Math.floor(100000+Math.random()*900000)}`,txHash:'0x'+Array.from({length:64},()=>Math.floor(Math.random()*16).toString(16)).join(''),blockTimestamp:new Date().toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}),employeeName:'Vansidian Enterprise Team',employeeRole:'September payroll run',disclosedAmount:total,batchRootHash:root,employeeCount:employees.length,circuitName:'processPayrollBatch (Compact v0.31.1)'});};
  return <section className="app-card overflow-hidden" aria-labelledby="payroll-title">
    <div className="flex flex-col gap-5 border-b border-[var(--border)] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><div className="flex items-center gap-2"><h2 id="payroll-title" className="text-lg font-semibold">September payroll</h2><span className="status-success rounded-full px-2 py-0.5 text-xs">Draft</span></div><p className="mt-1 text-sm text-[var(--text-muted)]">Review compensation and submit one private payroll proof.</p></div><button onClick={submit} disabled={!isConnected||isProcessing} className="app-button-primary px-4 py-2.5 text-sm font-semibold">{isProcessing?'Generating proof…':`Submit payroll · $${total.toLocaleString()}`}</button></div>
    <div className="grid grid-cols-2 border-b border-[var(--border)] bg-[var(--canvas)] sm:grid-cols-4">{[['Total payroll',`$${total.toLocaleString()}`],['Team members',String(employees.length)],['Pay date','Sep 30'],['Exceptions','0']].map(([k,v])=><div key={k} className="border-b border-r border-[var(--border)] p-4 sm:border-b-0 sm:p-5"><p className="text-xs text-[var(--text-muted)]">{k}</p><p className="mt-1 text-lg font-semibold">{v}</p></div>)}</div>
    <div className="flex flex-col gap-3 border-b border-[var(--border)] p-4 sm:flex-row sm:items-center sm:justify-between"><label className="relative block sm:w-72"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--text-subtle)]"/><span className="sr-only">Search team members</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search team members" className="w-full rounded-lg border border-[var(--border)] bg-[var(--surface-1)] py-2 pl-9 pr-3 text-sm placeholder:text-[var(--text-subtle)]"/></label><p className="text-xs text-[var(--text-muted)]">{shown.length} of {employees.length} team members</p></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-[var(--border)] text-xs text-[var(--text-muted)]"><th className="px-6 py-3 font-medium">Team member</th><th className="px-4 py-3 font-medium">Department</th><th className="px-4 py-3 text-right font-medium">Base</th><th className="px-4 py-3 text-right font-medium">Bonus</th><th className="px-4 py-3 text-right font-medium">Total</th><th className="px-6 py-3 text-right font-medium">Status</th></tr></thead><tbody>{shown.map(e=><tr key={e.id} className="border-b border-[var(--border)] last:border-0 hover:bg-[var(--surface-3)]"><td className="px-6 py-3.5"><p className="font-medium">{e.name}</p><p className="text-xs text-[var(--text-muted)]">{e.role}</p></td><td className="px-4 py-3.5 text-sm text-[var(--text-muted)]">{e.department}</td><td className="px-4 py-3.5 text-right font-mono text-sm">{isPublicMode?'Shielded':`$${e.salary.toLocaleString()}`}</td><td className="px-4 py-3.5 text-right"><button onClick={()=>toggle(e.id)} className="rounded-md px-2 py-1 font-mono text-xs text-[#b7a8ff] hover:bg-[var(--brand-soft)]" aria-label={`Toggle bonus for ${e.name}`}>{isPublicMode?'Shielded':e.bonus?`+$${e.bonus}`:'Add'}</button></td><td className="px-4 py-3.5 text-right font-mono text-sm font-medium">{isPublicMode?'Shielded':`$${(e.salary+e.bonus).toLocaleString()}`}</td><td className="px-6 py-3.5 text-right"><span className="inline-flex items-center gap-1.5 text-xs text-[#73d7aa]"><Check className="h-3.5 w-3.5"/>Ready</span></td></tr>)}</tbody></table></div>
    <div className="border-t border-[var(--border)] bg-[var(--surface-1)]"><button onClick={()=>setDetails(!details)} className="flex w-full items-center justify-between px-5 py-3 text-sm text-[var(--text-muted)] hover:text-white" aria-expanded={details}><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4"/>Proof and commitment details</span>{details?<ChevronUp className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}</button>{details&&<div className="grid gap-4 border-t border-[var(--border)] px-5 py-4 text-xs sm:grid-cols-2"><div><p className="mb-1 text-[var(--text-muted)]">Merkle batch root</p><code className="break-all text-[#b7a8ff]">{root}</code></div><div><p className="mb-1 text-[var(--text-muted)]">Circuit</p><code>processPayrollBatch · Compact v0.31.1</code></div></div>}</div>
  </section>;
};
